/**
 * Regenerates protocol/vectors.json from the real crypto implementation.
 *
 *   node scripts/gen-vectors.ts
 *
 * Both test suites assert against the output. Regenerating it is therefore a
 * deliberate act: if a change here makes the Rust tests fail, the change broke
 * compatibility with every blob already written under the old scheme.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  type Bytes,
  SUBKEY_INFO,
  aadForBlob,
  aadForJournal,
  aadForKdfCheck,
  blobIdFor,
  deriveKeys,
  deriveMasterKey,
  deriveSubkeyBytes,
  sealWithIv,
  toBase64,
  toHex,
  KDF_CHECK_LITERAL,
} from "../src/crypto.ts";

const utf8 = new TextEncoder();
const b = (s: string): Bytes => utf8.encode(s) as Bytes;

// Fixed, obviously-fake inputs. Low iteration count so the Rust suite stays
// fast in debug builds; the real count is carried in meta, and a client that
// ignored the parameter would fail this vector.
const SALT = new Uint8Array(32).map((_, i) => (i * 7 + 3) & 0xff) as Bytes;
const KDF = { alg: "PBKDF2-HMAC-SHA256" as const, salt: toBase64(SALT), iterations: 1000 };

// Deliberately non-ASCII: macOS hands back decomposed forms, so the NFC
// normalization in deriveMasterKey is load-bearing, not decorative.
const PASSPHRASE_NFC = "café-wachtwoord-ß-één";
const PASSPHRASE_NFD = PASSPHRASE_NFC.normalize("NFD");

const VAULT_ID = "1600203ea33bc4d1be6641c1546be18b";
const DEVICE_ID = "macbook";
const ENTRY_ID = "0f8c1d2e3a4b5c6d7e8f90a1b2c3d4e5";

const iv = (seed: number): Bytes =>
  new Uint8Array(12).map((_, i) => (seed + i * 31) & 0xff) as Bytes;

const master = await deriveMasterKey(PASSPHRASE_NFC, KDF);
const keys = await deriveKeys(master);

// A note, an empty file, and bytes that are not valid UTF-8 — the vault holds
// PNGs, so the binary path has to be covered by a vector too.
const MARKDOWN = b("# Standup\n\n- ship the thing\n- review PR\n");
const EMPTY = new Uint8Array(0) as Bytes;
const BINARY = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0xff, 0xfe, 0x00, 0x80]) as Bytes;

const JOURNAL_PAYLOAD = b(
  JSON.stringify({
    op: "put",
    path: "Work/Meetings/Standup.md",
    blobId: await blobIdFor(keys, MARKDOWN),
    size: MARKDOWN.length,
    mtime: 1757400000000,
  }),
);

const markdownId = await blobIdFor(keys, MARKDOWN);

const vectors = {
  $comment:
    "Cross-language test vectors for PROTOCOL.md §3. Generated by " +
    "plugin/scripts/gen-vectors.ts from the TypeScript implementation, and " +
    "asserted by both the TypeScript and the Rust test suites. If a change " +
    "here breaks the Rust tests, it has broken compatibility with data " +
    "already written — regenerate only when that is the intent.",
  protocol: 1,

  kdf: KDF,

  passphrase: {
    $comment:
      "Both forms must derive the same master key: the same characters typed " +
      "on macOS (NFD) and on Linux (NFC) must unlock the same vault.",
    nfc: PASSPHRASE_NFC,
    nfd: PASSPHRASE_NFD,
    masterKeyHex: toHex(master),
  },

  subkeys: {
    $comment: "HKDF-SHA256, 32-byte zero salt, one info string per purpose.",
    info: SUBKEY_INFO,
    contentHex: toHex(await deriveSubkeyBytes(master, SUBKEY_INFO.content)),
    metaHex: toHex(await deriveSubkeyBytes(master, SUBKEY_INFO.meta)),
    idHex: toHex(await deriveSubkeyBytes(master, SUBKEY_INFO.id)),
    checkHex: toHex(await deriveSubkeyBytes(master, SUBKEY_INFO.check)),
  },

  blobIds: {
    $comment: "HMAC-SHA256(k_id, plaintext), first 16 bytes, lowercase hex.",
    cases: [
      { name: "markdown", plaintextB64: toBase64(MARKDOWN), blobId: markdownId },
      { name: "empty", plaintextB64: toBase64(EMPTY), blobId: await blobIdFor(keys, EMPTY) },
      { name: "binary", plaintextB64: toBase64(BINARY), blobId: await blobIdFor(keys, BINARY) },
    ],
  },

  seal: {
    $comment:
      "iv || AES-256-GCM(plaintext, aad) || tag. The IVs here are fixed so the " +
      "output is reproducible; production code always uses a random IV. The " +
      "empty case is the minimum legal sealed value — 12-byte IV plus a " +
      "16-byte tag, nothing between — and exists to pin that boundary.",
    cases: [
      {
        name: "blob",
        key: "content",
        aad: aadForBlob(markdownId),
        ivHex: toHex(iv(0x10)),
        plaintextB64: toBase64(MARKDOWN),
        sealedB64: toBase64(await sealWithIv(keys.content, MARKDOWN, aadForBlob(markdownId), iv(0x10))),
      },
      {
        name: "blob-binary",
        key: "content",
        aad: aadForBlob("ffffffffffffffffffffffffffffffff"),
        ivHex: toHex(iv(0x20)),
        plaintextB64: toBase64(BINARY),
        sealedB64: toBase64(
          await sealWithIv(keys.content, BINARY, aadForBlob("ffffffffffffffffffffffffffffffff"), iv(0x20)),
        ),
      },
      {
        name: "blob-empty",
        key: "content",
        aad: aadForBlob("00000000000000000000000000000000"),
        ivHex: toHex(iv(0x50)),
        plaintextB64: toBase64(EMPTY),
        sealedB64: toBase64(
          await sealWithIv(keys.content, EMPTY, aadForBlob("00000000000000000000000000000000"), iv(0x50)),
        ),
      },
      {
        name: "journal",
        key: "meta",
        aad: aadForJournal(DEVICE_ID, ENTRY_ID),
        ivHex: toHex(iv(0x30)),
        plaintextB64: toBase64(JOURNAL_PAYLOAD),
        sealedB64: toBase64(
          await sealWithIv(keys.meta, JOURNAL_PAYLOAD, aadForJournal(DEVICE_ID, ENTRY_ID), iv(0x30)),
        ),
      },
      {
        name: "kdfCheck",
        key: "check",
        aad: aadForKdfCheck(VAULT_ID),
        ivHex: toHex(iv(0x40)),
        plaintextB64: toBase64(b(KDF_CHECK_LITERAL)),
        sealedB64: toBase64(
          await sealWithIv(keys.check, b(KDF_CHECK_LITERAL), aadForKdfCheck(VAULT_ID), iv(0x40)),
        ),
      },
    ],
  },

  identifiers: { vaultId: VAULT_ID, deviceId: DEVICE_ID, entryId: ENTRY_ID },
  kdfCheckLiteral: KDF_CHECK_LITERAL,
};

const out = fileURLToPath(new URL("../protocol/vectors.json", import.meta.url));
writeFileSync(out, JSON.stringify(vectors, null, 2) + "\n");
console.log(`wrote ${out}`);
